apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mak3r.demo/workloadselector: deployment-rabbitmq-ns-rabbitmq
  name: rabbitmq
  namespace: rabbitmq-ns
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      mak3r.demo/workloadselector: deployment-rabbitmq-ns-rabbitmq
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rabbitmq-ns-rabbitmq
        mak3r.demo/workloadselector: deployment-rabbitmq-ns-rabbitmq
    spec:
      containers:
      - image: rabbitmq:3-management
        imagePullPolicy: Always
        name: rabbitmq
        ports:
        - containerPort: 5672
          name: internal
          protocol: TCP
        - containerPort: 15672
          name: mgmt
          protocol: TCP
        - containerPort: 5672
          hostPort: 5672
          name: external
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      hostname: mq-demo
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
