apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-loadbalancer
  namespace: rabbitmq-ns
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: lb
    nodePort: 32461
    port: 8080
    protocol: TCP
    targetPort: 15672
  selector:
    mak3r.demo/workloadselector: deployment-rabbitmq-ns-rabbitmq
  sessionAffinity: None
  type: LoadBalancer
