apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: rabbitmq-ns
spec:
  ports:
  - name: clusterip
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    mak3r.demo/workloadselector: deployment-rabbitmq-ns-rabbitmq
  sessionAffinity: None
  type: ClusterIP
